# Generated by Django 4.1.2 on 2022-10-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=2022, verbose_name='Year Released'),
            preserve_default=False,
        ),
    ]
